name: studyapp
description: "Global Bible Tools Hebrew and Greek Study App"
publish_to: 'none'

version: 0.9.2+19

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  sqflite: ^2.4.2
  path: ^1.9.1
  database_builder: 
    path: database_builder
  shared_preferences: ^2.5.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  connectivity_plus: ^6.1.4
  archive: ^4.0.7
  http: ^1.4.0
  path_provider: ^2.1.5
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  unorm_dart: ^0.3.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true # needed for generating localization files
  fonts:
    - family: sbl
      fonts:
        - asset: assets/fonts/sbl_blit.ttf
  assets:
    - assets/databases/
    - assets/images/logo.png
