name: studyapp
description: "Global Bible Tools Hebrew and Greek Study App"
publish_to: 'none'

version: 0.3.5+8

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  sqflite: ^2.4.2
  path: ^1.9.1
  database_builder: 
    path: database_builder
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: sbl
      fonts:
        - asset: assets/fonts/sbl_blit.ttf
  assets:
    - assets/databases/
